### ISSUE TITLE
TypeError: got an unexpected keyword argument 'quality'

### ISSUE THREAD

**Issue by yingfansong** [THUNLP-AIPoet/MixPoet#12]
Traceback (most recent call last):
  File "train.py", line 80, in <module>
    main()
  File "train.py", line 76, in main
    train(mixpoet, tool, hps)
  File "train.py", line 53, in train
    mix_trainer.train(mixpoet, tool)
  File "C:\Users\yingf\Desktop\MixPoet\codes\mix_trainer.py", line 304, in train
  File "C:\Users\yingf\Desktop\MixPoet\codes\mix_trainer.py", line 247, in run_train
    logger.draw_curves()
  File "C:\Users\yingf\Desktop\MixPoet\codes\logger.py", line 422, in draw_curves
    fig.savefig(self.fig_path+"/latent_distance.png", dpi=300, quality=100, bbox_inches="tight")
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\site-packages\matplotlib\figure.py", line 3274, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\site-packages\matplotlib\backend_bases.py", line 2338, in print_figure
    result = print_method(
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\site-packages\matplotlib\backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\site-packages\matplotlib\_api\deprecation.py", line 385, in wrapper
    arguments = signature.bind(*inner_args, **inner_kwargs).arguments
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "C:\Users\yingf\anaconda3\envs\MixPoet\lib\inspect.py", line 3026, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'quality'

**Comment by 2119319622** [comment]
matplotLib的版本有问题，下载程推荐的那个最低版本试试
