### ISSUE TITLE
pickle数据加载错：_pickle.UnpicklingError: invalid load key, 'v'

### ISSUE THREAD

**Issue by xzby977** [THUNLP-AIPoet/MixPoet#4]
模型训练完成，执行python generate.py -v 1时出错：
**python generate.py -v 1**
vocabulary size: 7024
restore checkpoint from ../checkpoint/model_ckpt_mixfine_3e.tar
loading...
load state dic, params: 141...
loading poetry filter...
  rhythm dic loaded, level tone chars: 3304, oblique tone chars: 4301
  rhyme dic loaded, ambiguous rhyme chars: 67
Traceback (most recent call last):
  File "generate.py", line 122, in <module>
    main()
  File "generate.py", line 116, in main
    generate_manu(args)
  File "generate.py", line 38, in generate_manu
    generator = Generator()
  File "D:\AI\九歌\MixPoet-master\codes\generator.py", line 54, in __init__
    self.tool.get_ivocab(), self.hps.data_dir)
  File "D:\AI\九歌\MixPoet-master\codes\filter.py", line 43, in __init__
    self.__load_rhyme_dic(data_dir+"pingshui.txt", data_dir+"pingshui_amb.pkl")
  File "D:\AI\九歌\MixPoet-master\codes\filter.py", line 119, in __load_rhyme_dic
    self.__char_rhyme_map = pickle.load(fin)
_pickle.UnpicklingError: invalid load key, 'v'.
出错文件为pingshui_amb.pkl
请问各位老师是什么原因，如何解决，谢谢

**Comment by XiaoyuanYi** [comment]
@xzby977 
你好, 这有可能是下载的pingshui_amb.pkl文件有损坏, 或者编码的问题, 因为我们的pingshui_amb.pkl是在linux下生成的. 请尝试一下用git lfs clone重新下载相关数据. 如果还是不行的话, 我们之后会尝试上传一个Windows下编码生成的替代文件.

**Comment by xzby977** [comment]
感谢，期待新的数据文件
